version: "3.8"
services:

  netflux_db:
    image: mysql:latest
    container_name: netflux_db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - netflux-mysql-data:/var/lib/mysql

  netflux_redis:
    image: redis:6-alpine
    container_name: netflux_redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server

  netflux_api:
    image: node:lts-alpine
    container_name: netflux_api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c './wait-for netflux_db:${DB_PORT} -- yarn start'

volumes:
  netflux-mysql-data:
