version: '3.8'
services:
  netflux_db:
    image: mysql:latest
    container_name: netflux_db
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - netflux-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  netflux_redis:
    image: redis:6-alpine
    container_name: netflux_redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server

  netflux_api:
    image: node:lts-alpine
    container_name: netflux_api
    restart: always
    ports:
      - '${APP_PORT}:3333'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: sh -c './wait-for netflux_db:3306 -- yarn && yarn cache clean && yarn dev'

volumes:
  netflux-mysql-data:
