version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    ports: 
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server

  api:
    image: node:lts-alpine
    container_name: api
    restart: always
    ports: 
      - '3333:3333'
    depends_on: 
      - db
    volumes: 
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c './wait-for db:3306 -- yarn start'

volumes:
  mysql_data: 
