module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('movies',
    [{
      id: 1,
      title: 'Dark',
      description: 'A missing child causes four families to help each other for answers. What they could not imagine is that this mystery would be connected to innumerable other secrets of the small town.',
      poster_path: '/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
      backdrop_path: '/3lBDg3i6nn5R2NKFCJ6oKyUo2j5.jpg',
      genres: 80,
      year: 2017,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      title: 'Lucifer',
      description: "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
      poster_path: '/1sBx2Ew4WFsa1YY32vlHt079O03.jpg',
      backdrop_path: '/vauFEN12Exuck3nO9WWmjB1R5cJ.jpg',
      genres: 80,
      year: 2016,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      title: 'DreamWorks Dragons',
      description: 'From the creators of "How to Train Your Dragon" comes a new series that takes Hiccup and Toothless to the edge of adventure.',
      poster_path: '/fDzGH0jGhJMMxbgsb9JiC7Ep4uk.jpg',
      backdrop_path: '/l8MgpYzOl8ejMn1lKCKO73bMrGY.jpg',
      genres: 16,
      year: 2012,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 4,
      title: 'Ozark',
      description: 'A financial adviser drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.',
      poster_path: '/oy7Peo5iFIt9sNM59lN6csbJeX2.jpg',
      backdrop_path: '/hNaBXLiLTxMhtj7IFjOdJngXxxr.jpg',
      genres: 80,
      year: 2017,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 5,
      title: "Marvel's Daredevil",
      description: 'Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.',
      poster_path: '/QWbPaDxiB6LW2LjASknzYBvjMj.jpg',
      backdrop_path: '/qsnXwGS7KBbX4JLqHvICngtR8qg.jpg',
      genres: 28,
      year: 2015,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 6,
      title: '13 Reasons Why',
      description: "After a teenage girl's perplexing suicide, a classmate receives a series of tapes that unravel the mystery of her tragic choice.",
      poster_path: '/nel144y4dIOdFFid6twN5mAX9Yd.jpg',
      backdrop_path: '/sZb21d6EWKAEKZ9GrLQeMwX4cWN.jpg',
      genres: 18,
      year: 2017,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 7,
      title: 'Cable Girls',
      description: 'In 1920s Madrid, four women at the National Telephone Company ring in revolution as they deal with romance, envy and the modern workplace.',
      poster_path: '/lAwLmgq1zy0xJnusszmvWTLjFlO.jpg',
      backdrop_path: '/iHLexEHCET03oGwe22gbHw0BfLL.jpg',
      genres: 18,
      year: 2017,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 8,
      title: 'Star Wars: The Clone Wars',
      description: 'Yoda, Obi-Wan Kenobi, Anakin Skywalker, Mace Windu and other Jedi Knights lead the Grand Army of the Republic against the droid army of the Separatists.',
      poster_path: '/e1nWfnnCVqxS2LeTO3dwGyAsG2V.jpg',
      backdrop_path: '/m6eRgkR1KC6Mr6gKx6gKCzSn6vD.jpg',
      genres: 16,
      year: 2008,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 9,
      title: 'Dark Desire',
      description: 'Married Alma spends a fateful weekend away from home that ignites passion, ends in tragedy and leads her to question the truth about those close to her.',
      poster_path: '/uxFNAo2A6ZRcgNASLk02hJUbybn.jpg',
      backdrop_path: '/vmVeGFUTXEKwAUpFH9bZwow9zIk.jpg',
      genres: 18,
      year: 2020,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 10,
      title: 'Black Mirror',
      description: "A contemporary British re-working of The Twilight Zone with stories that tap into the collective unease about our modern world. \n\nOver the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence.",
      poster_path: '/pXeuSWSKgWUnhRFHZ4TjAUU8lbE.jpg',
      backdrop_path: '/p39K75uoZLwnhGlEAJxRG5xAD9y.jpg',
      genres: 18,
      year: 2011,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 11,
      title: 'Warrior Nun',
      description: 'After waking up in a morgue, an orphaned teen discovers she now possesses superpowers as the chosen Halo-Bearer for a secret sect of demon-hunting nuns.',
      poster_path: '/77OM9jMJ8nglaolHLwrAW7kvadV.jpg',
      backdrop_path: '/u2R4WKNvEQAfgiEl6kAOvj6AuFv.jpg',
      genres: 18,
      year: 2020,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 12,
      title: "Marvel's Jessica Jones",
      description: 'After a tragic ending to her short-lived super hero stint, Jessica Jones is rebuilding her personal life and career as a detective who gets pulled into cases involving people with extraordinary abilities in New York City.',
      poster_path: '/wkFdanlAaV39sSXeslImfRUj3jQ.jpg',
      backdrop_path: '/57JFnZqpG5OLgHdZY7Zf9dKcZ5U.jpg',
      genres: 18,
      year: 2015,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 13,
      title: 'The Protector',
      description: 'The epic adventure of Hakan, a young shopkeeper whose modern world gets turned upside down when he learns he’s connected to a secret, ancient order, tasked with protecting Istanbul.',
      poster_path: '/xoN4wJRzeaWBfuQDYPngJgN6y9t.jpg',
      backdrop_path: '/n5h1JNlTm3AdWoKZnGcZMgemt8S.jpg',
      genres: 10759,
      year: 2018,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 14,
      title: 'Anne with an E',
      description: 'A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.',
      poster_path: '/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg',
      backdrop_path: '/ywQtHG17LZhAFZyZtBflhtFMtJ7.jpg',
      genres: 18,
      year: 2017,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 15,
      title: 'Money Heist',
      description: 'To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.',
      poster_path: '/MoEKaPFHABtA1xKoOteirGaHl1.jpg',
      backdrop_path: '/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg',
      genres: 80,
      year: 2017,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 16,
      title: 'House of Cards',
      description: 'Set in present day Washington, D.C., House of Cards is the story of Frank Underwood, a ruthless and cunning politician, and his wife Claire who will stop at nothing to conquer everything. This wicked political drama penetrates the shadowy world of greed, sex and corruption in modern D.C.',
      poster_path: '/hKWxWjFwnMvkWQawbhvC0Y7ygQ8.jpg',
      backdrop_path: '/ex4kvQb0Ski5KL2fsnKQU2hV3oo.jpg',
      genres: 18,
      year: 2013,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 17,
      title: 'The Business of Drugs',
      description: 'To detail how drugs push people into risky — even deadly — behaviors, a former CIA analyst investigates the economics of six illicit substances.',
      poster_path: '/blyObONhcnleib1xqcwS9uvAfIM.jpg',
      backdrop_path: '/54f4FsZ4248sCrvzQnw6XXTFWWY.jpg',
      genres: 80,
      year: 2020,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 18,
      title: 'Stranger Things',
      description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
      poster_path: '/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg',
      backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
      genres: 18,
      year: 2016,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 19,
      title: 'Sex Education',
      description: 'Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.',
      poster_path: '/4Bph0hhnDH6dpc0SZIV522bLm4P.jpg',
      backdrop_path: '/61m8HGEWwE4q8oSz3AY5vl5F3BS.jpg',
      genres: 35,
      year: 2019,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 20,
      title: 'Cursed',
      description: 'In this fresh take on the Arthurian legend, teenager Nimue joins forces with mercenary Arthur on a quest to find Merlin and deliver an ancient sword.',
      poster_path: '/wrLC5kx0nEq9U0MyJD7dnOT6m5F.jpg',
      backdrop_path: '/uzUPwWSAheYKdavFCcod9M6y2rf.jpg',
      genres: 10759,
      year: 2020,
      netflix: true,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 21,
      title: 'Dilwale Dulhania Le Jayenge',
      description: 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
      poster_path: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
      backdrop_path: '/svYzz6A6xleZv5toTLAhigXd1DX.jpg',
      genres: 35,
      year: 1995,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 22,
      title: "Gabriel's Inferno",
      description: "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
      poster_path: '/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg',
      backdrop_path: '/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg',
      genres: 10749,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 23,
      title: 'Hamilton',
      description: 'Presenting the tale of American founding father Alexander Hamilton, this filmed version of the original Broadway smash hit is the story of America then, told by America now.',
      poster_path: '/h1B7tW0t399VDjAcWJh8m87469b.jpg',
      backdrop_path: '/uWVkEo9PWHu9algZsiLPi6sRU64.jpg',
      genres: 18,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 24,
      title: 'The Shawshank Redemption',
      description: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
      poster_path: '/5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg',
      backdrop_path: '/avedvodAZUcwqevBfm8p4G2NziQ.jpg',
      genres: 80,
      year: 1994,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 25,
      title: 'Steven Universe: The Movie',
      description: 'Two years after the events of "Change Your Mind", Steven (now 16 years old) and his friends are ready to enjoy the rest of their lives peacefully. However, all of that changes when a new sinister Gem arrives, armed with a giant drill that saps the life force of all living things on Earth. In their biggest challenge ever, the Crystal Gems must work together to save all organic life on Earth within 48 hours.',
      poster_path: '/8mRgpubxHqnqvENK4Bei30xMDvy.jpg',
      backdrop_path: '/re3ZvlKJg04iLpLRf1xTKHS2wLU.jpg',
      genres: 28,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 26,
      title: "Schindler's List",
      description: 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
      poster_path: '/c8Ass7acuOe4za6DhSattE359gr.jpg',
      backdrop_path: '/w2ezhZUk7ZJH9Mdk1Y6CTmaDRg5.jpg',
      genres: 18,
      year: 1993,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 27,
      title: 'Your Name.',
      description: 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
      poster_path: '/q719jXXEzOoYaps6babgKnONONX.jpg',
      backdrop_path: '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
      genres: 16,
      year: 2016,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 28,
      title: 'Parasite',
      description: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
      backdrop_path: '/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg',
      genres: 35,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 29,
      title: 'The Godfather',
      description: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      poster_path: '/iVZ3JAcAjmguGPnRNfWFOtLHOuY.jpg',
      backdrop_path: '/ejdD20cdHNFAYAN2DlqPToXKyzx.jpg',
      genres: 80,
      year: 1972,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 30,
      title: 'Me contro Te: Il film - La vendetta del Signor S',
      description: 'Luì and Sofì fight the terrible Signor S once again, this time he will be revealed to the public!!!',
      poster_path: '/sfeQTIRkJjWt8IPDSBcPqkrcaas.jpg',
      backdrop_path: '/wooZWiC4NWH0ahCSUOogEmVejHo.jpg',
      genres: 35,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 31,
      title: 'Spirited Away',
      description: 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
      poster_path: '/2TeJfUZMGolfDdW6DKhfIWqvq8y.jpg',
      backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
      genres: 16,
      year: 2001,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 32,
      title: 'The Godfather: Part II',
      description: 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
      poster_path: '/amvmeQWheahG3StKwIE1f7jRnkZ.jpg',
      backdrop_path: '/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg',
      genres: 80,
      year: 1974,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 33,
      title: 'We All Loved Each Other So Much',
      description: 'Gianni, Nicola and Antonio become close friends in 1944 while fighting the Nazis. After the end of the war, full of illusions, they settle down. The movie is a the story of the life of these three idealists and how they deal with the inevitable disillusionments of life.',
      poster_path: '/zGGWYpiKNwjpKxelPxOMqJnUgDs.jpg',
      backdrop_path: '/bh6yfB6I1N1WuMiX6K5HxGVZnja.jpg',
      genres: 35,
      year: 1974,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 34,
      title: 'Justice League Dark: Apokolips War',
      description: 'Earth is decimated after intergalactic tyrant Darkseid has devastated the Justice League in a poorly executed war by the DC Super Heroes. Now the remaining bastions of good – the Justice League, Teen Titans, Suicide Squad and assorted others – must regroup, strategize and take the war to Darkseid in order to save the planet and its surviving inhabitants.',
      poster_path: '/c01Y4suApJ1Wic2xLmaq1QYcfoZ.jpg',
      backdrop_path: '/sQkRiQo3nLrQYMXZodDjNUJKHZV.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 35,
      title: 'Pulp Fiction',
      description: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      poster_path: '/kK6iLyKi9Kg86qR2xPxOU94UEel.jpg',
      backdrop_path: '/eDMZmfnH50DDboUxTRnOYYpE9aY.jpg',
      genres: 80,
      year: 1994,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 36,
      title: 'Life Is Beautiful',
      description: 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
      poster_path: '/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg',
      backdrop_path: '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg',
      genres: 35,
      year: 1997,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 37,
      title: 'The Green Mile',
      description: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
      poster_path: '/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
      backdrop_path: '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
      genres: 80,
      year: 1999,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 38,
      title: "Mortal Kombat Legends: Scorpion's Revenge",
      description: 'After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.',
      poster_path: '/4VlXER3FImHeFuUjBShFamhIp9M.jpg',
      backdrop_path: '/vw3zNfzvnVNF7nIjpiEgcdznfeC.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 39,
      title: 'The Lord of the Rings: The Return of the King',
      description: "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
      backdrop_path: '/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg',
      genres: 28,
      year: 2003,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 40,
      title: 'Once Upon a Time in America',
      description: 'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.',
      poster_path: '/hBDHr3YihnuL46aeyEMhTchXkZP.jpg',
      backdrop_path: '/gUdk0FMw38DSUqpnLLHCAWN60he.jpg',
      genres: 18,
      year: 1984,
      netflix: false,
      trending: false,
      top_rated: true,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 41,
      title: 'Greyhound',
      description: 'A first-time captain leads a convoy of allied ships carrying thousands of soldiers across the treacherous waters of the “Black Pit” to the front lines of WW2. With no air cover protection for 5 days, the captain and his convoy must battle the surrounding enemy Nazi U-boats in order to give the allies a chance to win the war.',
      poster_path: '/AsdB9A2XGalCZVjlyG9tRf03IfW.jpg',
      backdrop_path: '/xXBnM6uSTk6qqCf0SRZKXcga9Ba.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 42,
      title: 'Snowpiercer',
      description: 'Set more than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.',
      poster_path: '/n6UNHZoiYj81abwmG38HbNjflDx.jpg',
      backdrop_path: '/dJBKKbrQIqcQ9EUbdM48dM8mso6.jpg',
      genres: 10765,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 43,
      title: 'Avengers: Endgame',
      description: "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      poster_path: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
      backdrop_path: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
      genres: 28,
      year: 2019,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 44,
      title: 'The Old Guard',
      description: "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
      poster_path: '/cjr4NWURcVN3gW5FlHeabgBHLrY.jpg',
      backdrop_path: '/m0ObOaJBerZ3Unc74l471ar8Iiy.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 45,
      title: 'The 100',
      description: "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
      poster_path: '/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg',
      backdrop_path: '/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg',
      genres: 18,
      year: 2014,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 46,
      title: 'Eurovision Song Contest: The Story of Fire Saga',
      description: 'Two small-town aspiring musicians chase their pop star dreams at a global music competition, where high stakes, scheming rivals and onstage mishaps test their bond.',
      poster_path: '/9zrbgYyFvwH8sy5mv9eT25xsAzL.jpg',
      backdrop_path: '/jMO1icztaUUEUApdAQx0cZOt7b8.jpg',
      genres: 35,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 49,
      title: 'Relic',
      description: 'When Edna, the elderly and widowed matriarch of the family, goes missing, her daughter Kay and granddaughter Sam travel to their remote family home to find her. Soon after her return, they start to discover a sinister presence haunting the house and taking control of Edna.',
      poster_path: '/a7dOnIr8S1AeFRR0UyfhKIN83Wi.jpg',
      backdrop_path: '/vpUUznNzW85xo02H16RaSxRNS1.jpg',
      genres: 18,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 50,
      title: 'Hanna',
      description: 'This thriller and coming-of-age drama follows the journey of an extraordinary young girl as she evades the relentless pursuit of an off-book CIA agent and tries to unearth the truth behind who she is. Based on the 2011 Joe Wright film.',
      poster_path: '/iYUtjx1EN4SVTgxd2TB4cZTGSQb.jpg',
      backdrop_path: '/6Fzyuwn8KeMCSqRILfdrDmCvmod.jpg',
      genres: 18,
      year: 2019,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 51,
      title: 'The Outpost',
      description: 'A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.',
      poster_path: '/hPkqY2EMqWUnFEoedukilIUieVG.jpg',
      backdrop_path: '/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 52,
      title: 'Desperados',
      description: 'A panicked young woman and her two best friends fly to Mexico to delete a ranting email she sent to her new boyfriend. On arrival, they run into her former beau, who soon gets caught up in their frantic scheme.',
      poster_path: '/hoUzSMxGu4Bm73EvH6B3iceFwW8.jpg',
      backdrop_path: '/k8H6Qp4uJ9WHArPQwDqCaW9g3Sj.jpg',
      genres: 35,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 53,
      title: 'The Invisible Man',
      description: "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
      poster_path: '/5EufsDwXdY2CVttYOk2WtYhgKpa.jpg',
      backdrop_path: '/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg',
      genres: 27,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 55,
      title: 'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
      description: 'Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.',
      poster_path: '/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
      backdrop_path: '/9xNOiv6DZZjH7ABoUUDP0ZynouU.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 56,
      title: 'Joker',
      description: 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
      poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
      backdrop_path: '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
      genres: 80,
      year: 2019,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 57,
      title: 'Palm Springs',
      description: 'When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated as they are unable to escape the venue, themselves, or each other.',
      poster_path: '/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg',
      backdrop_path: '/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg',
      genres: 35,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 58,
      title: 'Artemis Fowl',
      description: "Artemis Fowl is a 12-year-old genius and descendant of a long line of criminal masterminds. He soon finds himself in an epic battle against a race of powerful underground fairies who may be behind his father's disappearance.",
      poster_path: '/tI8ocADh22GtQFV28vGHaBZVb0U.jpg',
      backdrop_path: '/o0F8xAt8YuEm5mEZviX5pEFC12y.jpg',
      genres: 12,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 59,
      title: '365 Days',
      description: 'Massimo Torricelli, a young and handsome boss of a Sicilian Mafia family, has no other option but to takeover after his father has been assassinated. Laura is a sales director in a luxurious hotel in Warsaw. She has a successful career, but her private life lacks passion. She is taking one last shot to save her relationship. Together with her bone-headed boyfriend Martin and some other friends, she takes a trip to Sicily. She does not expect that Massimo, the most dangerous man on the island, will get in her way, kidnap her, hold her captive and give her 365 days - to fall in love with him.',
      poster_path: '/6KwrHucIE3CvNT7kTm2MAlZ4fYF.jpg',
      backdrop_path: '/27nn2YJBwY7a1etZ0AiIcOrIgu3.jpg',
      genres: 18,
      year: 2020,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 60,
      title: 'Journey to China: The Mystery of Iron Mask',
      description: 'The Russian Czar Peter the Great commissions Jonathan Green, an English traveller, to map the Far East territories of the Russian Empire. Green sets off on yet another long journey, full of unbelievable adventures, which eventually leads him to China. On his way, the famous cartographer makes breath-taking discoveries, meets mysterious creatures, Chinese princesses, deadly masters of oriental martial arts, and even Lun Van, the King of Dragons, himself. What could be more perilous than looking into the eyes of Viy? Only meeting him again… What will prevail this time — the unflinching scepticism of the scientist or ancient black magic, which has already gained influence over the Far East Lands?',
      poster_path: '/GAeK18hkfR6rzlo1vITvQhoEiW.jpg',
      backdrop_path: '/5yiCqzmxYv36GGdc05egCMHedbX.jpg',
      genres: 12,
      year: 2019,
      netflix: false,
      trending: true,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 62,
      title: 'Avengers: Infinity War',
      description: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
      poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
      backdrop_path: '/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg',
      genres: 28,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 63,
      title: 'Terminator: Dark Fate',
      description: 'Decades after Sarah Connor prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally and an enhanced super soldier to stop the deadliest Terminator yet.',
      poster_path: '/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg',
      backdrop_path: '/a6cDxdwaQIFjSkXf7uskg78ZyTq.jpg',
      genres: 28,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 66,
      title: 'Invasion',
      description: "After the fall of the alien ship, it took three years. The catastrophe turned the girl's life from Chertanovo and forever changed our view of the universe. It seems that this was the biggest test for all of us. But mankind does not yet know that very soon he will have to experience a new meeting.",
      poster_path: '/rpqfpSglhDpwihzsLaoketuYKbd.jpg',
      backdrop_path: '/cbJNZeFkiG4ggsNcwzBs6yeCXga.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 67,
      title: 'Dracula Untold',
      description: "Vlad Tepes is a great hero, but when he learns the Sultan is preparing for battle and needs to form an army of 1,000 boys, he vows to find a way to protect his family. Vlad turns to dark forces in order to get the power to destroy his enemies and agrees to go from hero to monster as he's turned into the mythological vampire, Dracula.",
      poster_path: '/m5h3NtZ2ZfryIHl1MvatmANvIqQ.jpg',
      backdrop_path: '/f02FFv77Rh62633YEjimv7C6JM3.jpg',
      genres: 28,
      year: 2014,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 68,
      title: 'Star Wars',
      description: 'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
      poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
      backdrop_path: '/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg',
      genres: 28,
      year: 1977,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 69,
      title: 'Star Wars: The Rise of Skywalker',
      description: 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
      poster_path: '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
      backdrop_path: '/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg',
      genres: 28,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 70,
      title: 'Train to Busan Presents: Peninsula',
      description: 'Peninsula takes place four years after Train to Busan as the characters fight to escape the land that is in ruins due to an unprecedented disaster.',
      poster_path: '/7S9RvfMBWSTlUZ4VbxDY7oLeenk.jpg',
      backdrop_path: '/oamFZb8Gj5NJ24OLDd07wyNVX4N.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 72,
      title: 'The Dark Knight',
      description: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
      poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
      genres: 28,
      year: 2008,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 74,
      title: 'Sonic the Hedgehog',
      description: 'Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.',
      poster_path: '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
      backdrop_path: '/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 75,
      title: 'Bloodshot',
      description: "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
      poster_path: '/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg',
      backdrop_path: '/lP5eKh8WOcPysfELrUpGhHJGZEH.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 76,
      title: 'Inception',
      description: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
      backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
      genres: 28,
      year: 2010,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 77,
      title: 'The Hobbit: The Battle of the Five Armies',
      description: "Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
      poster_path: '/xT98tLqatZPQApyRmlPL12LtiWp.jpg',
      backdrop_path: '/bVmSXNgH1gpHYTDyF9Q826YwJT5.jpg',
      genres: 28,
      year: 2014,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 78,
      title: 'Spider-Man: Far from Home',
      description: 'Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.',
      poster_path: '/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg',
      backdrop_path: '/5myQbDzw3l8K9yofUXRJ4UTVgam.jpg',
      genres: 28,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 79,
      title: 'The Gentlemen',
      description: 'American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.',
      poster_path: '/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg',
      backdrop_path: '/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 80,
      title: 'Divergent',
      description: "In a world divided into factions based on personality types, Tris learns that she's been classified as Divergent and won't fit in. When she discovers a plot to destroy Divergents, Tris and the mysterious Four must find out what makes Divergents dangerous before it's too late.",
      poster_path: '/lmIh6aeCQXA4sLt58l6qB1o54BE.jpg',
      backdrop_path: '/ipikQozG6cAtLqhaFqRneA0LI4o.jpg',
      genres: 28,
      year: 2014,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 83,
      title: 'Scoob!',
      description: 'In Scooby-Doo’s greatest adventure yet, see the never-before told story of how lifelong friends Scooby and Shaggy first met and how they joined forces with young detectives Fred, Velma, and Daphne to form the famous Mystery Inc. Now, with hundreds of cases solved, Scooby and the gang face their biggest, toughest mystery ever: an evil plot to unleash the ghost dog Cerberus upon the world. As they race to stop this global “dogpocalypse,” the gang discovers that Scooby has a secret legacy and an epic destiny greater than anyone ever imagined.',
      poster_path: '/jHo2M1OiH9Re33jYtUQdfzPeUkx.jpg',
      backdrop_path: '/fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg',
      genres: 12,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 86,
      title: 'Onward',
      description: 'In a suburban fantasy world, two teenage elf brothers embark on an extraordinary quest to discover if there is still a little magic left out there.',
      poster_path: '/f4aul3FyD3jv3v4bul1IrkWZvzq.jpg',
      backdrop_path: '/xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg',
      genres: 16,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 87,
      title: '40 Days and 40 Nights',
      description: "Matt Sullivan's last big relationship ended in disaster and ever since his heart's been aching and his commitment's been lacking. Then came Lent, that time of year when everybody gives something up. That's when Matt decides to go where no man's gone before and make a vow: No sex. Whatsoever. For 40 straight days. At first he has everything under control. That is until the woman of his dreams, Erica, walks into his life.",
      poster_path: '/5a60NuJToRAc0gijjI5IRSVGKL3.jpg',
      backdrop_path: '/yffyMavLTwBgVvCKMQProlKMzL3.jpg',
      genres: 35,
      year: 2002,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 89,
      title: 'Inside Out',
      description: "Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Riley's guiding emotions— Joy, Fear, Anger, Disgust and Sadness—live in Headquarters, the control centre inside Riley's mind, where they help advise her through everyday life and tries to keep things positive, but the emotions conflict on how best to navigate a new city, house and school.",
      poster_path: '/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg',
      backdrop_path: '/9cGSFGZVVLsrnbs0AFPDh6X2ynl.jpg',
      genres: 18,
      year: 2015,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 91,
      title: 'Jumanji: The Next Level',
      description: 'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.',
      poster_path: '/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg',
      backdrop_path: '/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg',
      genres: 12,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 92,
      title: 'Dolittle',
      description: 'After losing his wife seven years earlier, the eccentric Dr. John Dolittle, famed doctor and veterinarian of Queen Victoria’s England, hermits himself away behind the high walls of Dolittle Manor with only his menagerie of exotic animals for company. But when the young queen falls gravely ill, a reluctant Dolittle is forced to set sail on an epic adventure to a mythical island in search of a cure, regaining his wit and courage as he crosses old adversaries and discovers wondrous creatures.',
      poster_path: '/uoplwswBDy7gsOyrbGuKyPFoPCs.jpg',
      backdrop_path: '/xcUf6yIheo78btFqihlRLftdR3M.jpg',
      genres: 12,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 93,
      title: 'Monsters, Inc.',
      description: "James Sullivan and Mike Wazowski are monsters, they earn their living scaring children and are the best in the business... even though they're more afraid of the children than they are of them. When a child accidentally enters their world, James and Mike suddenly find that kids are not to be afraid of and they uncover a conspiracy that could threaten all children across the world.",
      poster_path: '/sgheSKxZkttIe8ONsf2sWXPgip3.jpg',
      backdrop_path: '/sDTnMOJ3H5wI38OxObmCtK7wfd5.jpg',
      genres: 16,
      year: 2001,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 94,
      title: 'Psych 2: Lassie Come Home',
      description: 'After Santa Barbara Police Chief Carlton Lassiter is ambushed and left for dead, Shawn and Gus return to help him and find themselves embroiled in a case involving the personal, the professional—and even the supernatural.',
      poster_path: '/2LXQUhkzo27jKotK7poHkNaw59B.jpg',
      backdrop_path: '/fHkOalncR4nYkUsiEhEN3Y20Nd2.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 95,
      title: 'The Kissing Booth',
      description: "When teenager Elle's first kiss leads to a forbidden romance with the hottest boy in high school, she risks her relationship with her best friend.",
      poster_path: '/7Dktk2ST6aL8h9Oe5rpk903VLhx.jpg',
      backdrop_path: '/xEKx7zPEjN6meomZ7OhV82Mm2jm.jpg',
      genres: 35,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 96,
      title: 'Trolls World Tour',
      description: 'Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.',
      poster_path: '/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg',
      backdrop_path: '/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg',
      genres: 12,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 97,
      title: 'Thor: Ragnarok',
      description: 'Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of an all-powerful new threat, the ruthless Hela.',
      poster_path: '/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg',
      backdrop_path: '/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg',
      genres: 28,
      year: 2017,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 98,
      title: 'Knives Out',
      description: "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
      poster_path: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
      backdrop_path: '/AbRYlvwAKHs0YuyNO6NX9ofq4l6.jpg',
      genres: 35,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 99,
      title: 'The F**k-It List',
      description: "After a prank blows up a studious high school senior's life, he shares a list of certain things he wishes he'd done differently — and maybe still can.",
      poster_path: '/oIxGqt2XKTLEKLHVffIv9hUlW0T.jpg',
      backdrop_path: '/1FlAXJdpBgBXFnFpKQo44J91yGc.jpg',
      genres: 35,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 100,
      title: 'Rango',
      description: 'When Rango, a lost family pet, accidentally winds up in the gritty, gun-slinging town of Dirt, the less-than-courageous lizard suddenly finds he stands out. Welcomed as the last hope the town has been waiting for, new Sheriff Rango is forced to play his new role to the hilt.',
      poster_path: '/6IeGcoIEpOj7pUtzBk8zNM54YYl.jpg',
      backdrop_path: '/anSPPInN5tY6Bk1sOwLLTJAFzTq.jpg',
      genres: 12,
      year: 2011,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 105,
      title: 'Alien',
      description: 'During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.',
      poster_path: '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
      backdrop_path: '/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg',
      genres: 27,
      year: 1979,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 106,
      title: 'The Hunt',
      description: "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
      poster_path: '/wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg',
      backdrop_path: '/naXUDz0VGK7aaPlEpsuYW8kNVsr.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 107,
      title: 'It Follows',
      description: "After carefree teenager Jay  sleeps with her new boyfriend, Hugh, for the first time, she learns that she is the latest recipient of a fatal curse that is passed from victim to victim via sexual intercourse. Death, Jay learns, will creep inexorably toward her as either a friend or a stranger. Jay's friends don't believe her seemingly paranoid ravings, until they too begin to see the phantom assassins and band together to help her flee or defend herself.",
      poster_path: '/kdxZZ04HFh98ZZBiTZNWHMexsGZ.jpg',
      backdrop_path: '/keEWjA5ykLJo851tIBFdmkxPxxh.jpg',
      genres: 27,
      year: 2015,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 108,
      title: 'Underwater',
      description: 'After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.',
      poster_path: '/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg',
      backdrop_path: '/ww7eC3BqSbFsyE5H5qMde8WkxJ2.jpg',
      genres: 28,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 109,
      title: 'Doctor Sleep',
      description: "Still irrevocably scarred by the trauma he endured as a child at the Overlook, Dan Torrance has fought to find some semblance of peace. But that peace is shattered when he encounters Abra, a courageous teenager with her own powerful extrasensory gift, known as the 'shine'. Instinctively recognising that Dan shares her power, Abra has sought him out, desperate for his help against the merciless Rose the Hat and her followers.",
      poster_path: '/p69QzIBbN06aTYqRRiCOY1emNBh.jpg',
      backdrop_path: '/sZAXOoOMyCbBskmqR0f4LShxXtw.jpg',
      genres: 18,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 110,
      title: 'Starfish',
      description: 'A unique, intimate and honest portrayal of a girl grieving for the loss of her best friend. That just happens to take place on the day the world ends as we know it.',
      poster_path: '/ellZ2dQLPVeWgd2fjf4arcZwALc.jpg',
      backdrop_path: '/mTbdEMXacCjSef38fvx3nbZGB83.jpg',
      genres: 18,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 111,
      title: 'It Chapter Two',
      description: "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
      poster_path: '/zfE0R94v1E8cuKAerbskfD3VfUt.jpg',
      backdrop_path: '/8moTOzunF7p40oR5XhlDvJckOSW.jpg',
      genres: 14,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 112,
      title: 'Midsommar',
      description: 'Several friends travel to Sweden to study as anthropologists a summer festival that is held every ninety years in the remote hometown of one of them. What begins as a dream vacation in a place where the sun never sets, gradually turns into a dark nightmare as the mysterious inhabitants invite them to participate in their disturbing festive activities.',
      poster_path: '/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg',
      backdrop_path: '/g6GtOfXtzDpY73ef7wludoorTti.jpg',
      genres: 18,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 113,
      title: 'The Turning',
      description: "A young woman quits her teaching job to be a private tutor (governess) for a wealthy young heiress who witnessed her parent's tragic death. Shortly after arriving, the girl's degenerate brother is sent home from his boarding school. The tutor has some strange, unexplainable experiences in the house and begins to suspect there is more to their story.",
      poster_path: '/uiMHiHp9eAjJty8rddoUnL9G5fU.jpg',
      backdrop_path: '/lYJDf7oa1r9JvRITN1M2Lzis01D.jpg',
      genres: 27,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 114,
      title: 'The Shining',
      description: "Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
      poster_path: '/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg',
      backdrop_path: '/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg',
      genres: 27,
      year: 1980,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 115,
      title: 'Seven Boxes',
      description: '7 People, 7 Hours, 7 Deadly Boxes. Past events have brought them together and they must now figure out why in order to survive.',
      poster_path: '/w5scyRxDpnGGUWeDd0xyD6AeYxV.jpg',
      backdrop_path: '/1Fb4bxxtay6KaDY1JQZfo5mN3sW.jpg',
      genres: 27,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 116,
      title: 'Fantasy Island',
      description: 'A group of contest winners arrive at an island hotel to live out their dreams, only to find themselves trapped in nightmare scenarios.',
      poster_path: '/8ZMrZGGW65ePWIgRn1260nA1uUm.jpg',
      backdrop_path: '/27WkMAcrLJYgmJcgbNvzMh2qw70.jpg',
      genres: 12,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 117,
      title: '10 Cloverfield Lane',
      description: 'After getting in a car accident, a woman is held in a shelter with two men, who claim the outside world is affected by a widespread chemical attack.',
      poster_path: '/84Dhwz93vCin6T1PX6ctSvWEuNE.jpg',
      backdrop_path: '/9G8SmOBWuo0ME6FIwCockkwbNMq.jpg',
      genres: 18,
      year: 2016,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 118,
      title: 'Split',
      description: 'Though Kevin has evidenced 23 personalities to his trusted psychiatrist, Dr. Fletcher, there remains one still submerged who is set to materialize and dominate all the others. Compelled to abduct three teenage girls led by the willful, observant Casey, Kevin reaches a war for survival among all of those contained within him — as well as everyone around him — as the walls between his compartments shatter apart.',
      poster_path: '/lli31lYTFpvxVBeFHWoe5PMfW5s.jpg',
      backdrop_path: '/9pkZesKMnblFfKxEhQx45YQ2kIe.jpg',
      genres: 27,
      year: 2017,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 119,
      title: 'The Predator',
      description: "When a kid accidentally triggers the universe's most lethal hunters' return to Earth, only a ragtag crew of ex-soldiers and a disgruntled female scientist can prevent the end of the human race.",
      poster_path: '/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg',
      backdrop_path: '/f4E0ocYeToEuXvczZv6QArrMDJ.jpg',
      genres: 28,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 121,
      title: 'The Nun',
      description: 'When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together they uncover the order’s unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of the same demonic nun that first terrorized audiences in “The Conjuring 2” as the abbey becomes a horrific battleground between the living and the damned.',
      poster_path: '/sFC1ElvoKGdHJIWRpNB3xWJ9lJA.jpg',
      backdrop_path: '/fgsHxz21B27hOOqQBiw9L6yWcM7.jpg',
      genres: 27,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 127,
      title: 'Fifty Shades of Grey',
      description: "When college senior Anastasia Steele steps in for her sick roommate to interview prominent businessman Christian Grey for their campus paper, little does she realize the path her life will take. Christian, as enigmatic as he is rich and powerful, finds himself strangely drawn to Ana, and she to him. Though sexually inexperienced, Ana plunges headlong into an affair -- and learns that Christian's true sexual proclivities push the boundaries of pain and pleasure.",
      poster_path: '/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg',
      backdrop_path: '/7IGKrY1f1KfwMipx9wZC4NRgIdF.jpg',
      genres: 18,
      year: 2015,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 128,
      title: 'Aladdin',
      description: 'A kindhearted street urchin named Aladdin embarks on a magical adventure after finding a lamp that releases a wisecracking genie while a power-hungry Grand Vizier vies for the same lamp that has the power to make their deepest wishes come true.',
      poster_path: '/ykUEbfpkf8d0w49pHh0AD2KrT52.jpg',
      backdrop_path: '/v4yVTbbl8dE1UP2dWu5CLyaXOku.jpg',
      genres: 12,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 129,
      title: 'Forrest Gump',
      description: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
      poster_path: '/clolk7rB5lAjs41SD0Vt6IXYLMm.jpg',
      backdrop_path: '/7c9UVPPiTPltouxRVY6N9uugaVA.jpg',
      genres: 35,
      year: 1994,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 130,
      title: 'Red Shoes and the Seven Dwarfs',
      description: 'Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.',
      poster_path: '/MBiKqTsouYqAACLYNDadsjhhC0.jpg',
      backdrop_path: '/bga3i5jcejBekr2FCGJga1fYCh.jpg',
      genres: 16,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 131,
      title: 'Emma.',
      description: 'In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.',
      poster_path: '/uHpHzbHLSsVmAuuGuQSpyVDZmDc.jpg',
      backdrop_path: '/5GbkL9DDRzq3A21nR7Gkv6cFGjq.jpg',
      genres: 35,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 132,
      title: 'Fifty Shades Freed',
      description: 'Believing they have left behind shadowy figures from their past, newlyweds Christian and Ana fully embrace an inextricable connection and shared life of luxury. But just as she steps into her role as Mrs. Grey and he relaxes into an unfamiliar stability, new threats could jeopardize their happy ending before it even begins.',
      poster_path: '/9ZedQHPQVveaIYmDSTazhT3y273.jpg',
      backdrop_path: '/9ywA15OAiwjSTvg3cBs9B7kOCBF.jpg',
      genres: 18,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 133,
      title: 'Grease',
      description: "Australian good girl Sandy and greaser Danny fell in love over the summer. But when they unexpectedly discover they're now in the same high school, will they be able to rekindle their romance despite their eccentric friends?",
      poster_path: '/czVhhAaSBFpakur7U8pOIDV9NUG.jpg',
      backdrop_path: '/koSWhCzMJfJOramu4KD0ZZifqpi.jpg',
      genres: 35,
      year: 1978,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 134,
      title: 'Little Women',
      description: 'Four sisters come of age in America in the aftermath of the Civil War.',
      poster_path: '/yn5ihODtZ7ofn8pDYfxCmxh8AXI.jpg',
      backdrop_path: '/lqxxwTRk0l7CubY6JkJdhnwJEkn.jpg',
      genres: 18,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 135,
      title: 'After',
      description: "Tessa Young is a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart. Entering her first semester of college, Tessa's guarded world opens up when she meets Hardin Scott, a mysterious and brooding rebel who makes her question all she thought she knew about herself -- and what she wants out of life.",
      poster_path: '/u3B2YKUjWABcxXZ6Nm9h10hLUbh.jpg',
      backdrop_path: '/997ToEZvF2Obp9zNZbY5ELVnmrW.jpg',
      genres: 18,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 136,
      title: 'Nater Guru',
      description: "A man tries to bring together his girlfriends' parents, who have been estranged for fifteen years because of disagreements, misunderstandings, and pride.",
      poster_path: '/1R3hwwMVlalodwTmEk1fE7AiMpr.jpg',
      backdrop_path: '/2NniMVeu28Cod7Cnkwy9lCsbJxz.jpg',
      genres: 35,
      year: 2003,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 137,
      title: 'Titanic',
      description: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
      poster_path: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
      backdrop_path: '/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg',
      genres: 18,
      year: 1997,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 138,
      title: 'Cinderela Pop',
      description: "Cintia is modern princess, she's connected, decided and loves music. This \"pop\" princess used to live with their parents in a huge castle with a nice view to the city. Every night she looked through the window and watch the view dreaming with a prince she didn't met yet. But one day her castle crumbles with everything around her, after her parents divorce she went to live with her aunt and stops believing in love.  What she didn't knew was that there was a charming prince in her history, that wanted to break the ice around our modern day cinderella.",
      poster_path: '/uL0TrrV5MHQFkwRxlho0dDKTwvm.jpg',
      backdrop_path: '/3tt3tp81aGboViMplQItugAI2RO.jpg',
      genres: 35,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 139,
      title: 'Sleeping Beauty',
      description: "A beautiful princess born in a faraway kingdom is destined by a terrible curse to prick her finger on the spindle of a spinning wheel and fall into a deep sleep that can only be awakened by true love's first kiss. Determined to protect her, her parents ask three fairies to raise her in hiding. But the evil Maleficent is just as determined to seal the princess's fate.",
      poster_path: '/hsQD3U3P8wkU63jgKg9TlK5oxK3.jpg',
      backdrop_path: '/bwZY9cTdiw00Uk3mA4bJz8HXoyB.jpg',
      genres: 16,
      year: 1959,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 140,
      title: 'Maleficent',
      description: "A beautiful, pure-hearted young woman, Maleficent has an idyllic life growing up in a peaceable forest kingdom, until one day when an invading army threatens the harmony of the land.  Maleficent rises to be the land's fiercest protector, but she ultimately suffers a ruthless betrayal – an act that begins to turn her heart into stone. Bent on revenge, Maleficent faces an epic battle with the invading King's successor and, as a result, places a curse upon his newborn infant Aurora. As the child grows, Maleficent realizes that Aurora holds the key to peace in the kingdom – and to Maleficent's true happiness as well.",
      poster_path: '/ik8PugpL41s137RAWEGTAWu0dPo.jpg',
      backdrop_path: '/xjotE7aFdZ0D8aGriYjFOtDayct.jpg',
      genres: 28,
      year: 2014,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 141,
      title: 'Father Soldier Son',
      description: 'When Sgt. First Class Brian Eisch is critically wounded in Afghanistan, it sets him and his sons on a journey of love, loss, redemption and legacy.',
      poster_path: '/7AIU4rH3ExBHQg92UHYxFYxP82M.jpg',
      backdrop_path: '/8IjnyGbzcX5Ulb4kXLnecgWDEYA.jpg',
      genres: 99,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 142,
      title: 'We Are One',
      description: 'Activists around the world fight injustice and drive social change in this documentary that follows their participation in the music video "Solidarité."',
      poster_path: '/hqAVnSjt2bwxUpugzgyZHTbO4sc.jpg',
      backdrop_path: '/1O5q5meJfZBBmdGtY0tocfU6tjd.jpg',
      genres: 99,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 146,
      title: 'Jackass 3D',
      description: 'Jackass 3D is a 3-D film and the third movie of the Jackass series. It follows the same premise as the first two movies, as well as the TV series. It is a compilation of various pranks, stunts and skits. Before the movie begins, a brief introduction is made by Beavis and Butt-head explaining the 3D technology behind the movie. The intro features the cast lining up and then being attacked by various objects in slow-motion. The movie marks the 10th anniversary of the franchise, started in 2000.',
      poster_path: '/tE9lFSCecv60Rl1DNUMj3urTxda.jpg',
      backdrop_path: '/ta1KuiThmEqVkW2kvOeOHmKIpmn.jpg',
      genres: 28,
      year: 2010,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 147,
      title: 'The Eagle Huntress',
      description: 'Follow Aisholpan, a 13-year-old girl, as she trains to become the first female in twelve generations of her Kazakh family to become an eagle hunter, and rise to the pinnacle of a tradition that has been typically been handed down from father to son for centuries.',
      poster_path: '/x0dZQM1vmDmFrOa7JoRDOTdLb3Q.jpg',
      backdrop_path: '/m6Rk92lA11e4gCisMb6I8OsWQ9t.jpg',
      genres: 12,
      year: 2016,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 148,
      title: 'American Factory',
      description: 'In post-industrial Ohio, a Chinese billionaire opens a new factory in the husk of an abandoned General Motors plant, hiring two thousand blue-collar Americans. Early days of hope and optimism give way to setbacks as high-tech China clashes with working-class America.',
      poster_path: '/7jH3dQOJ3CHMrp9tWsI3rRCDiaD.jpg',
      backdrop_path: '/r1QbTeE3qMXgKkGgFcHJCwDQrMg.jpg',
      genres: 99,
      year: 2019,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 149,
      title: 'After Porn Ends 2',
      description: "After Porn Ends 2 picks up where its predecessor left off and not only turns back the clock to meet the oldest living stars in adult film's history, but goes in depth with some of Its most current retirees and juxtaposes their experiences in a life after porn. Delving deeper into society's ongoing stigmas of race, misogyny, and the reality of decreasing opportunities for these former VHS box cover stars. For some, their careers in adult entertainment is accepted proudly and without regret. In fact, it seems to have proven to be the pathway to their current happiness and inner peace. For others, however, a career in porn has proven to be a conduit to certain despair as they struggle to find a way to bury their past and emerge with a new career or calling.",
      poster_path: '/rfItXrtDGILwsCdmgVxX79phFuI.jpg',
      backdrop_path: '/hlWkyIz2UxTcFVPw1u2c3qkPfhB.jpg',
      genres: 99,
      year: 2017,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 150,
      title: 'Free Solo',
      description: "Follow Alex Honnold as he attempts to become the first person to ever free solo climb Yosemite's 3,000 foot high El Capitan wall. With no ropes or safety gear, this would arguably be the greatest feat in rock climbing history.",
      poster_path: '/v4QfYZMACODlWul9doN9RxE99ag.jpg',
      backdrop_path: '/z2uuQasY4gQJ8VDAFki746JWeQJ.jpg',
      genres: 99,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 151,
      title: 'Money Heist: The Phenomenon',
      description: "A documentary on why and how 'Money Heist' sparked a wave of enthusiasm around the world for a lovable group of thieves and their professor.",
      poster_path: '/5E7gI52iwkXV9BEo5IfTKj36Lw7.jpg',
      backdrop_path: '/yEBBtk1eyZltGgJt8Z2zi3KIvvX.jpg',
      genres: 99,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 153,
      title: 'Uncle Tom',
      description: "In a collection of intimate interviews with some of America's most provocative black conservative thinkers, Uncle Tom takes a different look at being black in America.",
      poster_path: '/3OU5U2aERnQ0epiIOXrFWNzcmrI.jpg',
      backdrop_path: '/sfaNuzxiavI7Sk0STNKnYLU5mLb.jpg',
      genres: 99,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 154,
      title: 'Exit Through the Gift Shop',
      description: 'Banksy is a graffiti artist with a global reputation whose work can be seen on walls from post-hurricane New Orleans to the separation barrier on the Palestinian West Bank. Fiercely guarding his anonymity to avoid prosecution, Banksy has so far resisted all attempts to be captured on film. Exit Through the Gift Shop tells the incredible true story of how an eccentric French shop keeper turned documentary maker attempted to locate and befriend Banksy, only to have the artist turn the camera back on its owner.',
      poster_path: '/y6HK3PeQNeNLyruwtpCmV3TWuUx.jpg',
      backdrop_path: '/2HByjixHeh5XwNCmSOF5RitwzwR.jpg',
      genres: 99,
      year: 2010,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 155,
      title: '13th',
      description: "An in-depth look at the prison system in the United States and how it reveals the nation's history of racial inequality.",
      poster_path: '/tcKNWD6IFPPsvkpvyZ548naz0is.jpg',
      backdrop_path: '/yLGeoh6HJEdA2qYmIPJ4Q2vPHdy.jpg',
      genres: 99,
      year: 2016,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 156,
      title: 'Miss Americana',
      description: 'A raw and emotionally revealing look at one of the most iconic artists of our time during a transformational period in her life as she learns to embrace her role not only as a songwriter and performer, but as a woman harnessing the full power of her voice.',
      poster_path: '/z1HiEB1UEfdA5fPkngekjQ2vlCC.jpg',
      backdrop_path: '/A7AjlQTR1UlaNSYwwPRQ5gQTHyf.jpg',
      genres: 99,
      year: 2020,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 157,
      title: 'After Porn Ends 3',
      description: "After Porn Ends 3 continues to explore whether a career as an adult performer is inherently damaging to the balance of a perfomer's life once retired.",
      poster_path: '/6wwOzuSZCNZ0aDbLnwqqtzm6f04.jpg',
      backdrop_path: '/55Anuv1GtRUr8LZS0lkxtKMtl3W.jpg',
      genres: 99,
      year: 2018,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 158,
      title: 'This Is It',
      description: 'A compilation of interviews, rehearsals and backstage footage of Michael Jackson as he prepared for his series of sold-out shows in London.',
      poster_path: '/ml3Mt6tlBnhmyUpQeBeQ11L0QW8.jpg',
      backdrop_path: '/4qL7XSVyTMYm3k9khLO71LII77Z.jpg',
      genres: 99,
      year: 2009,
      netflix: false,
      trending: false,
      top_rated: false,
      creators: '',
      cast: '',
      created_at: new Date(),
      updated_at: new Date(),
    }]),

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('movies', null, {}),
};
